// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var View = require("../src/View.js");

Jest.describe("keyOf", (function (param) {
        Jest.test("t", (function (param) {
                var nameTInString = View.t_keyToString(/* Name */0);
                return Jest.Expect.toEqual("name", Jest.Expect.expect(nameTInString));
              }));
        Jest.test("t1", (function (param) {
                var nameT1InString = View.t1_keyToString(/* FirstName */0);
                return Jest.Expect.toEqual("firstName", Jest.Expect.expect(nameT1InString));
              }));
        return Jest.test("t2", (function (param) {
                      var nameT2InString = View.t2_keyToString(/* Name */0);
                      return Jest.Expect.toEqual("name", Jest.Expect.expect(nameT2InString));
                    }));
      }));

Jest.describe("toArray", (function (param) {
        Jest.test("check array length", (function (param) {
                var length = View.t8_toArray.length;
                return Jest.Expect.toEqual(2, Jest.Expect.expect(length));
              }));
        Jest.test("The first item is 'Name'", (function (param) {
                var first = View.t8_toArray[0];
                return Jest.Expect.toEqual("Name", Jest.Expect.expect(first));
              }));
        return Jest.test("The second item is 'Age'", (function (param) {
                      var first = View.t8_toArray[1];
                      return Jest.Expect.toEqual("Age", Jest.Expect.expect(first));
                    }));
      }));

Jest.describe("Polyvari toArray", (function (param) {
        Jest.test("check array length", (function (param) {
                var length = View.t9_toArray.length;
                return Jest.Expect.toEqual(2, Jest.Expect.expect(length));
              }));
        Jest.test("The first item is 'Name'", (function (param) {
                var first = View.t9_toArray[0];
                return Jest.Expect.toEqual("Name", Jest.Expect.expect(first));
              }));
        return Jest.test("The second item is 'Age'", (function (param) {
                      var first = View.t9_toArray[1];
                      return Jest.Expect.toEqual("Age", Jest.Expect.expect(first));
                    }));
      }));

/*  Not a pure module */
