// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var View = require("../src/View.js");

Jest.describe("keyOf", (function (param) {
        Jest.test("t", (function (param) {
                var nameTInString = View.t_keyToString(/* Name */0);
                return Jest.Expect.toEqual("name", Jest.Expect.expect(nameTInString));
              }));
        Jest.test("t1", (function (param) {
                var nameT1InString = View.t1_keyToString(/* FirstName */0);
                return Jest.Expect.toEqual("firstName", Jest.Expect.expect(nameT1InString));
              }));
        return Jest.test("t2", (function (param) {
                      var nameT2InString = View.t2_keyToString(/* Name */0);
                      return Jest.Expect.toEqual("name", Jest.Expect.expect(nameT2InString));
                    }));
      }));

/*  Not a pure module */
