// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");

Jest.describe("", (function (param) {
        return Jest.test("", (function (param) {
                      var stringifyName = "name";
                      return Jest.Expect.toEqual("name", Jest.Expect.expect(stringifyName));
                    }));
      }));

/*  Not a pure module */
