// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function t_keyToString(key) {
  if (key) {
    return "age";
  } else {
    return "name";
  }
}

function t1_keyToString(key) {
  if (key) {
    return "lastName";
  } else {
    return "firstName";
  }
}

function t2_keyToString(key) {
  if (key) {
    return "age";
  } else {
    return "name";
  }
}

exports.t_keyToString = t_keyToString;
exports.t1_keyToString = t1_keyToString;
exports.t2_keyToString = t2_keyToString;
/* No side effect */
